[tool.ruff]
line-length = 88
exclude = ["__pycache__", ".venv", "outputs", "data"]

[tool.ruff.lint]
extend-ignore = ["E203"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"